### ISSUE TITLE
Add most popular tags routes

### ISSUE THREAD

**Issue by jchekanoff** [rzwink/ohioready-api#13]
to align with Brandon's new [design](https://invis.io/XKWIQF9Y2MG#/412383371_Menu) for filters, we need a route to get the most popular tags for each of the three types: region, source, and tag.

<img width="956" alt="image" src="https://user-images.githubusercontent.com/28504852/78516668-63b0a500-7788-11ea-9954-0145aa0779be.png">

**Comment by rzwink** [comment]
I've added a "popularity" attribute to the /tag/ and /publisher/ endpoints.  Does that work for you?
